### ISSUE TITLE
caller to **612 do not ring

### ISSUE THREAD

**Issue by kirk-loeten** [Aypac/Arduino-TR-064-SOAP-Library#16]
![bildschirmfoto 2019-01-26 um 16 26 16](https://user-images.githubusercontent.com/35734454/51789270-76dce380-2187-11e9-9577-49406a20714d.png)

I have the 7490 with FritzOS 07.01 it is necessary to activate "Wahlhilfe" for the DECT phones. Now the Caller works.

**Comment by kirk-loeten** [comment]
Yes it is the solution, but wait, i write a small manual of all necessary Fritzbox configs for the wiki. Is a german part in the Wiki usefull?

**Comment by Aypac** [comment]
Ok, great!
Do you mean wiki pages written in German? Not sure about that. Most users seem to be German right now (also considering, that AVM is a German company), but I would like to keep it open to everyone. So if you want to write both German and English, that is fine, otherwise I personally would prefer English.

About the images: you can post German ones for now, I might replace it at some point with according English pictures.

**Comment by Aypac** [comment]
Wrote a first [draft](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/wiki/Q&A:-I-want-to-use-DECT-phones-with-this-library,-but-it-is-not-working!). Please feel free to comment/translate into German.

**Comment by Aypac** [comment]
Hi Christian,

I am working on a major update for this library right now. Unfortunately, I do not have any DECT phones, so I was wondering if you might find the time to test the `caller.ino` in [that branch](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/tree/branch-auto-refresh) for me.

Best,
René

**Comment by kirk-loeten** [comment]
Hi Rene,

I tested the callWahlhilfe() function and it doesn’t work. I use the code from Travis_CI_test with the connection.init() and it works.

The callDect() function need the connection.init() to.

I use …
 - ESP32-WROOM-32 (select in ARDUINO 1.8.3 FireBeetle-ESP32)
 - FritzBox 7490 with Fritz!OS 7.11
 - FRITZ!Powerline 546E

Best, Christian
