### ISSUE TITLE
Authentication token/nonce refresh?

### ISSUE THREAD

**Issue by dl9sec** [Aypac/Arduino-TR-064-SOAP-Library#18]
Hi,
I use the library to read out the current power values of two FRITZ!DECT 210 smartplugs.
Basically this works great within an interval of 10s after init and between each request to the smartplugs (both readouts directly after each other with a pause of 10s to the next request cycle).
Now it seems, that the authentication token/nonce seems to loose its validation after a specific time.
When I increase the interval to e.g. 30s, the first request to the first smartplug fails with status "Unauthenticated" and error 503 "UPnPError" at the "Challenge", while the second request to the other smartplug works fine.
Is there a suitable way to refresh the authentication token/nonce after a longer period? Or should i call an init immediately before requesting the smartplugs?
Thank you.
Regards, Thorsten

**Comment by Aypac** [comment]
Hi Thorsten,
good to hear that you found a new great application for the library! If you have it working, I would love if you could boil your script down and add it to the examples :)

Towards your question: I remember encountering the problem myself when I created the library. I thought I fixed it by automatically re-running the init (as part of the library). As far as I remember, there is no way to refresh a nonce after it becomes invalid (other then just re-running the init procedure), but I guess you could simply poll some random value to *keep* it valid (unless you want to send the ESP to sleep in the interim). However, I'm not sure, if I ever tested the automatic check it in production. Maybe the error message you encounter is also slightly different from what I got (which might lead to my code not even realizing that the request failed due to an expired nonce). I'll check it tomorrow and come back to you (you can of course also take a look, the library is actually rather simple, the only part that took some figuring out is the nonce procedure itself). In the meantime, I also don't see any disadvantage to simply re-initializing.

**Comment by Aypac** [comment]
It actually even sounds like a doing a dummy request before doing your two actual requests would also help.

**Comment by dl9sec** [comment]
Hi,
thanks for the reply. It was bad weather the last day, so there was much time to dig into the problem :-)
Actually i did exactly this, to do a dummy call to refresh the nonce. Maybe this could be a new public method to your library:
```
void refreshNonce(void)
{
  // Do a dummy request which will result in an authentication error, but will refresh the nonce
  String req[][2] = {{"NewAssociatedDeviceIndex", "1"}};

  tr064conn.action("urn:dslforum-org:service:WLANConfiguration:1", "GetGenericAssociatedDeviceInfo", req, 1);
  
}
```
You can find my example here:
https://github.com/dl9sec/ArduinoSIP/tree/master/examples/LaundryNotifier
Maybe i will strip down the code as a sample for read out those smartplugs...

Regards, Thorsten

**Comment by Aypac** [comment]
Hi Thorsten,
I just checked what happens in the library. As I remembered, I introduced some error-handling, but unfortunately in a somewhat stupid way; if the request fails, it re-initializes the nonce, however, it does not repeat the request. So in effect, your method simply calls `initNonce()` in a complicated fashion.
I started putting together a fix (together with some improved documentation) [in this branch](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/tree/branch-auto-refresh), but its not working yet.

Also truly testing it might take a few days (because my provider decided to prevent me from using a fritz!box, so I have to set up a testing rig). But once I made it to compile again, you can test it there.

Anyway, I think for now, you can just always call `initNonce()` after your longer break without any real disadvantage to that.

Best,
René

**Comment by Aypac** [comment]
Well, actually it compiles now, so you can give it a shot if you want :) Otherwise I'll test it one of these days.

**Comment by dl9sec** [comment]
Will try it and keep you in the loop :-)

**Comment by dl9sec** [comment]
Ok, i tested the "branch-auto-refresh" and removed my refreshNonce() function and call.
Result is the same as at the master branch. the first request ends up in an error, the second request works.
Calling initNonce() will not work because it is a private method...

**Comment by Aypac** [comment]
Ok, thanks for the testing. Do you also have some debug output? I'll take a look later today.

**Comment by dl9sec** [comment]
Do you need the serial console output?

**Comment by Aypac** [comment]
Yeah, I think that might help to understand what is happening.

**Comment by dl9sec** [comment]
Here it is:
[dl9sec_log.txt](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/files/3149182/dl9sec_log.txt)

The request to the DECT210 devices is made every 30s with
```
float getPwrAIN(const char *FbApiAIN)
{
  String params[][2] = {{"NewAIN", FbApiAIN}};
  String req[][2] = {{"NewMultimeterPower", ""}};

  tr064conn.action("urn:dslforum-org:service:X_AVM-DE_Homeauto:1", "GetSpecificDeviceInfos", params, 1, req, 1);

  float power = (float)((req[0][1]).toInt()) / 100.0;
  
  return power;
}
```
Hope this helps.
Thanks for your efforts...

**Comment by Aypac** [comment]
Thanks :)
Yeah, so this is what I feared initially. The HTTP code is 200 (good), but the XML says no-good 'Unauthenticated'. So I'm manually checking for that as well now. Can you test again?

**Comment by dl9sec** [comment]
Tried again. Unfortunately it is getting worse ;-)
See the log:
[dl9sec_log_20190507_1.txt](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/files/3153342/dl9sec_log_20190507_1.txt)

Now, i get no valid (means authenticated) response anymore...

**Comment by Aypac** [comment]
I almost fixed it already yesterday evening, but I didn't quiet find the time to finish. I'm gonna be out for the weekend and most of next week, so probably I won't be able to finish this soon. You can either just locally move the `initNonce()` function from private to public in the `tr064.h` and use it (future-proof, since this will also be done with the next update) or simply use the function you proposed for now (which is incidentally pretty much the `initNonce` anyway). I'll set up my test rig hopefully on the WE of the 18th and let you know when I have a new version you can try.
Cheers,
René

P.S.: Feel free to also try to fix it yourself and create a pull request :)

**Comment by dl9sec** [comment]
Hi René,
thank you very much. No problem at all, I have a workaround and a running system.
Let me know if i can do some further testing for you...

Regards, Thorsten

**Comment by Aypac** [comment]
Hi.
I spent some time yesterday and today and overhauled a good part of the library. It should be much more robust now. I already tested it a bit on my setup, but I don't have any phones or smartplugs to play with -- can you give it another try?

**Comment by dl9sec** [comment]
Hi René,
great stuff! Seems to work like a charm now :-)
```
11:26:26.306 -> 
11:26:26.306 -> Connecting to dl9sec_WLAN
11:26:26.306 -> 
11:26:26.306 -> WiFi connected to: 192.168.0.251
11:26:26.306 -> Initialize TR-064 connection...
11:26:57.825 -> AIN01: 0.05 W (avg.), State; 0
11:26:57.825 -> AIN02: 0.06 W (avg.), State; 0
11:27:27.856 -> [action]<error> got an unauthenticated error. Using the new nonce and trying again in 3s.
11:27:31.926 -> AIN01: 0.11 W (avg.), State; 0
11:27:31.926 -> AIN02: 0.12 W (avg.), State; 0
11:28:01.957 -> [action]<error> got an unauthenticated error. Using the new nonce and trying again in 3s.
11:28:05.829 -> AIN01: 0.16 W (avg.), State; 0
11:28:05.829 -> AIN02: 0.18 W (avg.), State; 0
11:28:35.838 -> [action]<error> got an unauthenticated error. Using the new nonce and trying again in 3s.
11:28:39.899 -> AIN01: 0.21 W (avg.), State; 0
11:28:39.933 -> AIN02: 0.24 W (avg.), State; 0
11:29:09.949 -> [action]<error> got an unauthenticated error. Using the new nonce and trying again in 3s.
11:29:14.019 -> AIN01: 0.21 W (avg.), State; 0
11:29:14.019 -> AIN02: 0.23 W (avg.), State; 0
11:29:44.018 -> [action]<error> got an unauthenticated error. Using the new nonce and trying again in 3s.
11:29:48.129 -> AIN01: 0.21 W (avg.), State; 0
11:29:48.129 -> AIN02: 0.23 W (avg.), State; 0
```
Will do a long term testing over the weekend. If something unexpected appears, i will post it here.
Thank you very much for your efforts...

Regards, Thorsten

**Comment by Aypac** [comment]
Hi Thorsten,
that is great news! Have you been able to do some more long-term testing?

**Comment by dl9sec** [comment]
Hi René,

yes :-)
Everything is working great and stable. I would suggest to close the issue.
Thanks again for you efforts...

Regards, Thorsten

**Comment by Aypac** [comment]
Hey Thorsten,
I was just about to integrate your example into the library, but noticed, that you included a copyright. I am not 100% sure, if it is compatible with the license I chose for this library ([MIT license](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/blob/master/LICENSE)). Would you mind if I changed the license text in my copy to the MIT license text?

**Comment by Aypac** [comment]
Ok, I think I found a good in-between solution. I added to my license, that certain parts are not part of the license and then left yours untouched. Maybe you can let me know, if that is okay for you. You can find it in the [same branch](https://github.com/Aypac/Arduino-TR-064-SOAP-Library/tree/branch-auto-refresh).

**Comment by dl9sec** [comment]
:-D
Yes, that's what I had suggested too, but you were faster.

The licenses are "incompatible" only in the advertising clause, but the suggestion you made will satisfy the license conditions. But i think this isn't a real problem at all, because every single file of the repository can have its own license (which doesn't make it easier for a licensee indeed :-) ).
And my copyright for my portion of the code will retain anyway.
So if someone wants to use/copy/modify your library he can do this under MIT conditions, nothing changes for the library itself . If he/she/it doesn't want to satisfy the BSD-3-Clause conditions for my portion of the examples it has to be omitted in further use.

So thank you for taking care of licensing issues (not much people do this).

Please change "Torsten" to "Thorsten" in the README.md (I am very proud of the additional h ;-) )

When will you merge? So i can change my example too and delete the refreshNonce part...

Regards, Thorsten
